### ISSUE TITLE
Logging Settings

### ISSUE THREAD

**Issue by payneBrandon** [usdot-jpo-ode/jpo-s3-deposit#21]
The current logging settings are proving problematic - I'm seeing growing log file sizes in excess of 37GB on a single container. To help combat this issue, the AWS Depositor should be configured with a default logging level of warn rather than debug. Additionally, the logback.xml file should include a maxFileSize so the file cannot grow indefinitely. 

It can also be a bit complex to work out the differences between the logback settings and docker logs. I recommend that the documentation is updated to reflect these differences and how to adjust the logback settings to be in line with the docker logging settings.

**Comment by dan-du-car** [comment]
This issue is closed with the resolution.
